[[maps]]
name = "Digitale farbige Orthophotos 2025 (DOP20RGB)"
path = "berlin/geoportal/luftbilder/2025-dop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2025 (DOP20RGB)"

[[maps]]
name = "Digitale farbige TrueOrthophotos 2024 (DOP20RGBI)"
path = "berlin/geoportal/luftbilder/2024-dop20rgbi"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2024 (DOP20RGBI)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/aff8a8a5-2b48-44e8-949b-ea5f7d382a4f"

[[maps]]
name = "Digitale farbige TrueOrthophotos 2023 (DOP20RGBI)"
path = "berlin/geoportal/luftbilder/2023-dop20rgbi"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2024 (DOP20RGBI)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/c68a287b-7ad0-4cc9-87f5-2cffebaf7113"

[[maps]]
name = "Digitale farbige TrueOrthophotos 2022 (DOP20RGBI)"
path = "berlin/geoportal/luftbilder/2022-dop20rgbi"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2024 (DOP20RGBI)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/c68a287b-7ad0-4cc9-87f5-2cffebaf7113"

[[maps]]
name = "Digitale farbige Orthophotos 2021 (DOP20RGBI)"
path = "berlin/geoportal/luftbilder/2021-dop20rgbi"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2021 (DOP20RGBI)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/ef0c8276-78af-4444-969f-d01bb7d3c841"

[[maps]]
name = "Digitale farbige TrueOrthophotos 2020 (TrueDOP20RGB) - Sommerbefliegung"
path = "berlin/geoportal/luftbilder/2020-truedop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige TrueOrthophotos 2020 (TrueDOP20RGB)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/95a1430d-04e9-434b-ba1e-9cd9f0e673b6"

[[maps]]
name = "Digitale farbige Orthophotos 2020 (DOP20RGB)"
path = "berlin/geoportal/luftbilder/2020-dop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2020 (DOP20RGB)"

[[maps]]
name = "Digitale Color-Infrarot-TrueOrthophotos 2020 (TrueDOP20CIR) - Sommerbefliegung"
path = "berlin/geoportal/luftbilder/2020-truedop20cir"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale Color-Infrarot-TrueOrthophotos 2020 (TrueDOP20CIR)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/95a1430d-04e9-434b-ba1e-9cd9f0e673b6"

[[maps]]
name = "Digitale Color-Infrarot-Orthophotos 2020 (DOP20CIR) - Sommerbefliegung"
path = "berlin/geoportal/luftbilder/2020-dop20cir"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale Color-Infrarot-Orthophotos 2020 (DOP20CIR)"

[[maps]]
name = "Digitale farbige Orthophotos 2019 (DOP20RGB)"
path = "berlin/geoportal/luftbilder/2019-dop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2019 (DOP20RGB)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/5b664b77-ca23-41cc-aba6-312245b559dd"

[[maps]]
name = "Digitale farbige Orthophotos 2018 (DOP20RGB)"
path = "berlin/geoportal/luftbilder/2018-dop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2018 (DOP20RGB)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/6cc4151c-7031-4c73-b3a6-43b27b2e3b62"

[[maps]]
name = "Digitale farbige Orthophotos 2017 (DOP20RGB)"
path = "berlin/geoportal/luftbilder/2017-dop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2017 (DOP20RGB)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/947b53e4-f014-3f12-b7a9-f6438f29223e"

[[maps]]
name = "Digitale farbige Orthophotos 2016 (DOP20RGB)"
path = "berlin/geoportal/luftbilder/2016-dop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2016 (DOP20RGB)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/eed6a16b-f86d-3ebe-8c92-0c7d32a6b465"

[[maps]]
name = "Digitale Color-Infrarot-Orthophotos 2016 (DOP20CIR)"
path = "berlin/geoportal/luftbilder/2016-dop20cir"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale Color-Infrarot-Orthophotos 2016 (DOP20CIR)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/eed6a16b-f86d-3ebe-8c92-0c7d32a6b465"

[[maps]]
name = "Digitale farbige Orthophotos 2015 (DOP20RGB)"
path = "berlin/geoportal/luftbilder/2015-dop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2015 (DOP20RGB)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/f81f42b6-0d14-353c-84dc-fafd55962710"

[[maps]]
name = "Digitale Color-Infrarot-Orthophotos 2015 (DOP20CIR)"
path = "berlin/geoportal/luftbilder/2015-dop20cir"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale Color-Infrarot-Orthophotos 2015 (DOP20CIR)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/f81f42b6-0d14-353c-84dc-fafd55962710"

[[maps]]
name = "Digitale farbige Orthophotos 2014 (DOP20RGB)"
path = "berlin/geoportal/luftbilder/2014-dop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2014 (DOP20RGB)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/e7b59db7-553a-3a47-93a5-70889f6dc77b"

[[maps]]
name = "Digitale farbige Trueorthophotos 2013"
path = "berlin/geoportal/luftbilder/2013-truedop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Trueorthophotos 2013"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/1b214cf5-ef58-3ca9-975a-ebbf9ffa568f"

[[maps]]
name = "Digitale farbige Orthophotos 2011 (DOP20RGB)"
path = "berlin/geoportal/luftbilder/2011-dop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2011 (DOP20RGB)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/72928789-80fe-3e71-93c4-ba16f46f1b75"

[[maps]]
name = "Digitale farbige Orthophotos 2010 (DOP20RGB)"
path = "berlin/geoportal/luftbilder/2010-dop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2010 (DOP20RGB)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/6213d0b9-00ff-36e7-89e4-0b72d846c66a"

[[maps]]
name = "Digitale Color-Infrarot-Orthophotos 2010 (DOP20CIR)"
path = "berlin/geoportal/luftbilder/2010-dop20cir"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale Color-Infrarot-Orthophotos 2010 (DOP20CIR)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/6213d0b9-00ff-36e7-89e4-0b72d846c66a"

[[maps]]
name = "Digitale farbige Orthophotos 2009 (DOP20RGB)"
path = "berlin/geoportal/luftbilder/2009-dop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2009 (DOP20RGB)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/8f70d448-6df2-3181-8944-eb27cf582743"

[[maps]]
name = "Digitale farbige Orthophotos 2007 (DOP20RGB)"
path = "berlin/geoportal/luftbilder/2007-dop20rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2007 (DOP20RGB)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/de32d147-d803-3340-a4be-ed0119b0bc48"

[[maps]]
name = "Digitale Schwarz-Weiß-Orthophotos 2006 (DOP15PAN)"
path = "berlin/geoportal/luftbilder/2006-dop15pan"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale Schwarz-Weiß-Orthophotos 2006 (DOP15PAN)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/b97ca27d-61cc-355b-8905-79ed0c4aa9b7"

[[maps]]
name = "Digitale Color-Infrarot-Orthophotos 2005 (DOP20CIR)"
path = "berlin/geoportal/luftbilder/2005-dop15cir"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale Color-Infrarot-Orthophotos 2005 (DOP20CIR)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/bfcbef8b-540c-4227-987b-356f6a7d7792"

[[maps]]
name = "Digitale farbige Orthophotos 2004 (DOP25RGB)"
path = "berlin/geoportal/luftbilder/2004-dop25rgb"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale farbige Orthophotos 2004 (DOP25RGB)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/7980cb5c-2c9a-3649-9e47-6b6413d2d88e"

[[maps]]
name = "Digitale Schwarz-Weiß-Orthophotos 2002 (DOP40PAN)"
path = "berlin/geoportal/luftbilder/2002-dop40pan"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Digitale Schwarz-Weiß-Orthophotos 2002 (DOP40PAN)"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/5aaeead0-f953-36c7-ad57-8eda40a1a9ee"

[[maps]]
name = "Luftbilder 1953, Maßstab 1:22 000"
path = "berlin/geoportal/luftbilder/1953"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Luftbilder 1953, Maßstab 1:22 000"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/6b746499-7354-3a3a-aa70-60e1fb37f993"

[[maps]]
name = "Luftbilder 1928, Maßstab 1:4 000"
path = "berlin/geoportal/luftbilder/1928"
attribution.text = "Senatsverwaltung für Stadtentwicklung, Bauen und Wohnen Berlin / Luftbilder 1928, Maßstab 1:4 000"
attribution.href = "https://gdi.berlin.de/geonetwork/srv/ger/catalog.search#/metadata/6b746499-7354-3a3a-aa70-60e1fb37f993"
